services:
  routewise-postgres-prod:
    image: postgres:15-alpine
    container_name: routewise-postgres-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: routewise_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  routewise-redis-prod:
    image: redis:7-alpine
    container_name: routewise-redis-prod
    ports:
      - "6380:6379"
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  routewise-backend-prod:
    image: routewise-backend:latest
    container_name: routewise-backend-prod
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: routewise-postgres-prod
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: routewise_db
      JWT_SECRET: prod_secret_key_123
      JWT_EXPIRES_IN: 24h
      GEMINI_API_KEY: "AIzaSyDq778HMw3PiPwRmj1__vvwNfUquEQtyh8"
      CORS_ORIGIN: "https://lionpark-routewise.devmindrift.net,https://bulkconnections-routewise.devmindrift.net,https://lionpark-routewise.devmindirftsolutions.net,https://bulkconnections-routewise.devmindirftsolutions.net,https://lionpark-routewise.mindriftsolutions.net,https://bulkconnections-routewise.mindriftsolutions.net"
    ports:
      - "3011:3001"
    depends_on:
      routewise-postgres-prod:
        condition: service_healthy
      routewise-redis-prod:
        condition: service_healthy

  mindrift-lionspark-weigh8-prod:
    image: mindrift-lionspark-weigh8:latest
    container_name: mindrift-lionspark-weigh8-prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://routewise-api.devmindrift.net
      - NEXT_PUBLIC_SITE_ID=1
    ports:
      - "3010:3000"
    depends_on:
      - routewise-backend-prod

  weigh8-bulkconnections-prod:
    image: weigh8-bulkconnections:latest
    container_name: weigh8-bulkconnections-prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://routewise-api.devmindrift.net
    ports:
      - "3012:3000"
    depends_on:
      - routewise-backend-prod

volumes:
  postgres_data_prod:
  redis_data_prod:
